services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - ../.env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - ../.env
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  inception:
    driver: bridge