version: "3.8"

services:
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

    wordpress:
      image: busybox
      command: sh -c "sleep 3600"
      networks:
        - inception

volumes:
  wordpress_data:
    driver: local

networks:
  inception:
    driver: bridge
