version: "3.8"

services:
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env

volumes:
  wordpress_data:
    driver: local

networks:
  inception:
    driver: bridge
