FROM debian:buster

RUN apt-get update && apt-get install -y \
	php7.3 \
	php7.3-fpm \
	php7.3-mysql \
	mariadb-client \
	curl \
	wget \
	tar \
	less \
	&& rm -rf /var/lib/apt/lists/*

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && \
	mv wp-cli.phar /usr/local/bin/wp

RUN mkdir -p /var/www/html

COPY setup.sh /setup.sh
RUN chmod +x /setup.sh

WORKDIR /var/www/html

EXPOSE 9000

CMD ["bash", "/setup.sh"]
