FROM debian:buster

RUN apt-get update && apt-get install -y nginx openssl

RUN mkdir -p /etc/nginx/ssl && \
chmod 700 /etc/nginx/ssl && \
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-keyout /etc/nginx/ssl/localhost.key \
-out /etc/nginx/ssl/localhost.crt \
-subj "C=BR/ST=SaoPaulo/L=SaoPaulo/O=42SP/OU=42/CN=localhost"

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
