name: Inception CI

on:
  push:
    branches: [ main ]
    paths:
      - 'srcs/**'
      - 'docker-compose.yml'
      - '.github/workflows/inception_biuld.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'srcs/**'
      - 'docker-compose.yml'
      - '.github/workflows/inception_biuld.yml'

concurrency:
  group: nginx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nginx-only:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set nginx
        run: |
          docker compose build nginx

      - name: Start containers
        run: |
          docker compose up -d nginx

      - name: List containers
        run: |
            docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

      - name: Test Port 443 (HTTPS)
        run: |
          set -e
          ATTEMPTS=25
          SLEEP=3
          echo "Aguardando HTTPS em https://localhost ..."
          for i in $(seq 1 $ATTEMPTS); do
            CODE=$(curl -sk -o /dev/null -w '%{http_code}' https://localhost/ || true)
            if echo "$CODE" | grep -Eq '^(200|301|302)$'; then
              echo "OK: HTTP $CODE"
              exit 0
            fi
            echo "Tentativa $i/$ATTEMPTS código=$CODE"
            docker compose ps nginx
            sleep $SLEEP
          done
          echo "FALHA: não obteve resposta aceitável."
          docker compose logs nginx || true
          docker exec nginx ss -tlpn || true
          exit 1

      - name: Verificar processo e porta dentro do container
        run: |
          docker exec nginx ss -tlpn
          docker exec nginx nginx -t

      - name: Logs (sucesso)
        if: success()
        run: docker compose logs --no-color nginx

      - name: Teardown
        if: always()
        run: docker compose down -v
