name: Inception CI - Makefile Test

on:
  push:
    branches: [ main ]
    paths:
      - 'Makefile'
      - 'srcs/**'
      - 'docker-compose.yml'
      - '.env'
      - '.github/workflows/inception_biuld.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Makefile'
      - 'srcs/**'
      - 'docker-compose.yml'
      - '.env'
      - '.github/workflows/inception_biuld.yml'

concurrency:
  group: makefile-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  makefile-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar Makefile
        run: |
          ls -la Makefile
          cat Makefile

      - name: Testar make build
        run: make build

      - name: Testar make up
        run: make up

      - name: Aguardar containers (30s)
        run: sleep 30

      - name: Testar make status
        run: make status

      - name: Testar make logs (sample)
        run: timeout 10s make logs || true

      - name: Verificar se containers estão rodando
        run: |
          docker ps
          docker compose ps

      - name: Testar make down
        run: make down

      - name: Verificar se containers pararam
        run: |
          docker ps
          if [ $(docker ps -q | wc -l) -eq 0 ]; then
            echo "✅ Todos os containers foram parados"
          else
            echo "❌ Ainda há containers rodando"
            exit 1
          fi

      - name: Testar make clean
        run: make clean

      - name: Cleanup final
        if: always()
        run: |
          docker compose down -v || true
          docker system prune -af || true